AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ServiceName:
    Type: String
    Default: Test
    Description: Stage that can be added to resource names

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ["", [!Ref ServiceName, "TestFunctionA" ]]
      Handler: test_function.lambda_handler
      CodeUri: test/
      Runtime: python2.7
      Policies:
        Statement:
          - Action:
              - 'codepipeline:*'
              - 'logs:*'
            Effect: Allow
            Resource: '*'

Outputs:
  TestFunction:
    Description: Test lambda function name
    Value: !Ref TestFunction
    Export:
      Name: !Join ["", [!Ref ServiceName, "TestFunctionA" ]]