version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies - `pwd`"
      -
      - cd lambda && npm install sequelize
      - echo "dependencies install completed `date`"
  build:
    commands:
      - echo Build started on `date`
      - echo "Installing dependencies - `pwd`"
      - cd ..
      - echo "Installing dependencies - `pwd`"
      - aws cloudformation package --template-file app-sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file app-output_sam.yaml || exit 0
      - aws cloudformation package --template-file test-sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file test-output_sam.yaml || exit 0
      - cat app-output_sam.yaml
      - cat test-output_sam.yaml
  post_build:
    commands:
      - echo Running post_build commands


artifacts:
  files:
    - app-output_sam.yaml
    - test-output_sam.yaml
  discard-paths: yes
